os: linux
language: go
go: 1.4.2
install: go get github.com/tools/godep
before_script: make dep-restore
script: make test-verbose
after_success:
  - "cd $GOROOT/src && GOOS=darwin GOARCH=amd64 ./make.bash --no-clean && cd -"
  - make package
deploy:
  provider: releases
  api_key:
    secure: Zz7LR7RybJ6DQ0FEyGNspKkkefgDUsltu+cwR2qnTrUjlJa9FAGfvv26ArwbNmff4iTq/cbDOcmDjhBBxi97b0aUn4hdz9jmPhC9WZZ045/jQA2I8wj0zy3a6zaJwF4oTWHH7qQiiMmn+ZAIFfC7zpVpk0M7JO4q5G4MZi+X/zs=
  file:
    - escarole-linux.tgz
    - escarole-darwin.tgz
  on:
    repo: albertrdixon/escarole
    tags: true
